### ISSUE TITLE
Clicking on Change color crashes godot

### ISSUE THREAD

**Issue by nonunknown** [mychalkboard/MyChalkBoard#1]
So, I'm trying chalkboard on my pc, and when I click to change the color it crashes godot with the following message:

![image](https://user-images.githubusercontent.com/58845030/118493076-175bc680-b6f7-11eb-9dd0-9c0c1b5691e6.png)

**Comment by mychalkboard** [comment]
Which version are you using? Also, instead of clicking to change colors in the project, you use the Z and X keys.

**Comment by nonunknown** [comment]
I'm using godot mono 3.3 rc2

**Comment by mychalkboard** [comment]
Can you try with 3.3? I do not encounter such a problem when I try it on Windows.

**Comment by nonunknown** [comment]
if you look at the message its related to viewport, when its called on save which I think you store it as sprite, maybe because I've increased the viewport node size!

**Comment by mychalkboard** [comment]
Thank you, based on what you told, I tried with different scenarios but did not get an error. Can you more explain the scenario where you are having the problem? It's looks like an exception. If I could get the same error I would love to fix it.

**Comment by nonunknown** [comment]
I can send you my fork, I'm adding more features, like a larger board, Zoom in-out and more, so you can try to fix it, And I can finish my PR. 

Here: https://github.com/nonunknown/MyChalkBoard

just get it and try to replicate the error!

**Comment by mychalkboard** [comment]
I understood what you want to do.I've reviewed your fork.

It takes a lot of change to do this. You will need to evaluate the container in which the drawings are stacked in a separate viewport. Because the camera2D object changes the values of the scene's viewport.

In this way, applying zoom will not be efficient as it is a texture-based drawing experience. To make this smoother, you need to change the entire structure. For example, even if you zoom in, the texture of the board should not change. The brush texture quality should not change either, so you have to draw with drawAPI from the beginning at every zoom. This brings you to make different optimizations.

Let me offer you the improvements that can be made to suit the project structure, they can be easily integrated into this structure.

- Ability to change brush size.
- To be able to scroll freely on the board by pressing the Space key.
- Optional drop-down gui menu for tools.
- Options to share the board. Saving the drawing on the board as a picture. Ability to share on Twitter with the Twitter API, if possible.
- Again as a sharing option; Making multi-person online drawings by linking to the board using godot's multiplayer api.
